### ISSUE TITLE
etherpad lite server crash on abort fileupload

### ISSUE THREAD

**Issue by clayu** [redhog/ep_fileupload#22]
When uploading a large file, if you leave the page during the upload **incoming_form.js** emits an error. The error propagates up and crashes the server. See below

Error: Request aborted
    at IncomingMessage.<anonymous> (/ep_fileupload/node_modules/formidable/lib/incoming_form.js:120:19)
    at IncomingMessage.emit (events.js:92:17)
    at abortIncoming (http.js:1916:11)
    at CleartextStream.serverSocketCloseListener (http.js:1928:5)
    at CleartextStream.emit (events.js:117:20)
    at tls.js:694:10
    at process._tickDomainCallback (node.js:486:13)

**Comment by JohnMcLear** [comment]
try wrap it in a try catch or put in some error handling for the function please :)
